#!/usr/bin/env bash
# make_trade_fixtures.sh — Gate-3 fixture generation (plan §7.1 step 4).
#
# Plays TWO saves from the Route 117 Day Care spot to the Mauville Pokémon
# Center 2F wireless counter under uncapped FF (offline: no netdrv session,
# so FF is available) using testdata/fixtures/emerald_park.inputs, in-game
# saves there, and snapshots the results:
#
#   testdata/fixtures/emerald_parkedA.sav   (AUSTIN — copy of the user save)
#   testdata/fixtures/emerald_parkedB.sav   (CLONEB — distinct trainer clone,
#                                            regenerated via clone_sav.py)
#
# The originals are never touched (DECISIONS.md user decision 1: .sav
# fixtures are gitignored and regenerated by this script).
# Exit 0 = both fixtures written and verified (park EVT sequence, final map
# == Pokémon Center 2F 0x060A, in-game save flushed, party intact).
# Run inside WSL/Linux.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"

ROM="$REPO/testdata/Pokemon - Emerald Version (USA, Europe).gba"
BIOS_DIR="$REPO/testdata"
SRC_SAV="$REPO/testdata/Pokemon Emerald All Shiny Fixed.sav"
BIN="$REPO/sdl/gpsp_sdl"
PARK="$REPO/testdata/fixtures/emerald_park.inputs"
FIX="$REPO/testdata/fixtures"
TIMEOUT_S="${TIMEOUT_S:-600}"

ART="$SCRIPT_DIR/artifacts/parkfix-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$ART"

fail() { echo "FAIL: $*" | tee -a "$ART/verdict.txt"; exit 1; }
note() { echo "$*" | tee -a "$ART/verdict.txt"; }

[ -x "$BIN" ] || fail "sdl/gpsp_sdl not built (make -C sdl)"
[ -f "$ROM" ] || fail "test ROM missing"
[ -f "$SRC_SAV" ] || fail "user save missing"

# CLONEB is derived, deterministic, regenerated every time (self-verifying).
python3 "$SCRIPT_DIR/clone_sav.py" "$SRC_SAV" "$FIX/emerald_cloneB.sav" \
    --name CLONEB --tid 33333 | tee -a "$ART/verdict.txt" \
    || fail "clone_sav.py refused"

park_one() { # $1 = side letter, $2 = source sav
  local side="$1" src="$2"
  local work="$ART/park$side.sav" log="$ART/park$side.log"
  cp "$src" "$work"
  SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy \
  timeout "$TIMEOUT_S" "$BIN" \
      --rom "$ROM" --bios-dir "$BIOS_DIR" --save "$work" \
      --log "$log" --dump-dir "$ART" \
      --script "$PARK" --ff >"$ART/park$side.stdout" 2>&1
  local rc=$?
  [ "$rc" = "0" ] || fail "side $side: park run rc=$rc (see $log)"
  grep -q "ap_mark text=park_done" "$log" || fail "side $side: no park_done"
  grep -q "ap_val name=park_loc2 val=0x0000060a" "$log" \
      || fail "side $side: not parked on PC2F"
  grep -q "^EVT sram_flush" "$log" || fail "side $side: no in-game save flush"
  python3 "$SCRIPT_DIR/read_party.py" "$work" >"$ART/party$side.txt" \
      || fail "side $side: parked save unreadable"
  grep -q "party_count=3" "$ART/party$side.txt" \
      || fail "side $side: party damaged"
  cp "$work" "$FIX/emerald_parked$side.sav"
  note "side $side: parked fixture written ($(md5sum "$FIX/emerald_parked$side.sav" | cut -d' ' -f1))"
}

park_one A "$SRC_SAV"
park_one B "$FIX/emerald_cloneB.sav"

note "PASS: emerald_parkedA.sav + emerald_parkedB.sav ready (artifacts: $ART)"
exit 0
