#!/usr/bin/env bash
# run_trade_test.sh — Gate 3: autonomous Emerald<->Emerald Union Room trade
# between two DESKTOP twin instances over the netdrv UDP driver with
# injected impairment (default 5% loss + 30 ms jitter, the plan §5 Phase-3
# hardening condition).  RetroArch is not involved anywhere.
#
# Normal mode:
#   HOST = emerald_parkedB.sav (CLONEB) runs emerald_trade_host.inputs:
#     enters the Union Room, registers its party slot-2 Magcargo on the
#     trading board requesting DRAGON, accepts the incoming trade.
#   JOIN = emerald_parkedA.sav (AUSTIN) runs emerald_trade_join.inputs:
#     enters the Union Room, offers its slot-1 Salamence at the board.
#   Both ride the full link trade (CB2_LinkTrade animation + the game's own
#   automatic in-game save, CB2_SaveAndEndWirelessTrade) back to the field.
#
#   TRADE ORACLE (asserted on BOTH sides, from RAM logs AND the saved .sav):
#     let a0 = parkedA slot-1 (personality,species), b1 = parkedB slot-2.
#     After the trade: join party slot 1 == b1 and host party slot 2 == a0,
#     each different from what that slot held before.  RAM: EVT ap_val
#     pre0/pre1/post0/post1 (gPlayerParty personalities); disk:
#     read_party.py on the post-run .sav (proves the in-game save contains
#     the traded mon).  Plus: EVT session_start + peer_connected both sides,
#     post-trade sram_flush on both, end map == Union Room (0x3C19), clean
#     EVT exit code=0, and driver health: overflow=0 drop_crc=0 drop_mal=0,
#     acked>0 (RELIABLE contract respected under impairment).
#
# --disconnect mode:
#   HOST runs emerald_trade_host_disc.inputs; when the JOIN logs
#   `ap_mark text=trade_anim` (mid trade animation) the harness waits 8 s
#   and SIGKILLs it.  Asserts: host survives with the game's own
#   communication-error dialog (EVT host_error_dialog + BMP screenshot of
#   CB2_PrintErrorMessage), no crash, clean EVT exit code=0.
#
# Fixtures: regenerated by tools/e2e/make_trade_fixtures.sh (invoked
# automatically when missing).  Exit 0 = pass.  Artifacts in
# tools/e2e/artifacts/trade[disc]-<timestamp>/.  Run inside WSL/Linux.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Serialise against every other ad-hoc test on this machine.  PPSSPP's
# AdhocServer port and /dev/shm/PPSSPP_ID are global, so SANDBOX_ROOT does
# NOT make two concurrent runs independent -- they corrupt each other and
# the symptom looks like a transport regression.  See adhoc_lock.sh.
. "$SCRIPT_DIR/adhoc_lock.sh"; adhoc_lock
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"

ROM="$REPO/testdata/Pokemon - Emerald Version (USA, Europe).gba"
BIOS_DIR="$REPO/testdata"
BIN="$REPO/sdl/gpsp_sdl"
FIX="$REPO/testdata/fixtures"

MODE=trade
[ "${1:-}" = "--disconnect" ] && MODE=tradedisc

PORT="${PORT:-19019}"
LOSS="${LOSS:-5}"
JITTER="${JITTER:-30}"
TIMEOUT_S="${TIMEOUT_S:-700}"

ART="$SCRIPT_DIR/artifacts/$MODE-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$ART/hostd" "$ART/joind"

fail() { echo "FAIL: $*" | tee -a "$ART/verdict.txt"; exit 1; }
note() { echo "$*" | tee -a "$ART/verdict.txt"; }

[ -x "$BIN" ] || fail "sdl/gpsp_sdl not built (make -C sdl)"
[ -f "$ROM" ] || fail "test ROM missing"

if [ ! -f "$FIX/emerald_parkedA.sav" ] || [ ! -f "$FIX/emerald_parkedB.sav" ]; then
  note "parked fixtures missing — generating (make_trade_fixtures.sh)"
  bash "$SCRIPT_DIR/make_trade_fixtures.sh" || fail "fixture generation failed"
fi

HOST_SCRIPT="$FIX/emerald_trade_host.inputs"
[ "$MODE" = "tradedisc" ] && HOST_SCRIPT="$FIX/emerald_trade_host_disc.inputs"

cp "$FIX/emerald_parkedB.sav" "$ART/host.sav"
cp "$FIX/emerald_parkedA.sav" "$ART/join.sav"

# Pre-trade identities of the mons that change hands (oracle inputs).
python3 "$SCRIPT_DIR/read_party.py" "$ART/host.sav" >"$ART/pre_host.txt" \
  || fail "cannot decode parkedB"
python3 "$SCRIPT_DIR/read_party.py" "$ART/join.sav" >"$ART/pre_join.txt" \
  || fail "cannot decode parkedA"
A0_PERS=$(awk '/^mon slot=0 /{print $3}' "$ART/pre_join.txt" | cut -d= -f2)
A0_SPEC=$(awk '/^mon slot=0 /{print $5}' "$ART/pre_join.txt" | cut -d= -f2)
B1_PERS=$(awk '/^mon slot=1 /{print $3}' "$ART/pre_host.txt" | cut -d= -f2)
B1_SPEC=$(awk '/^mon slot=1 /{print $5}' "$ART/pre_host.txt" | cut -d= -f2)
[ -n "$A0_PERS" ] && [ -n "$B1_PERS" ] || fail "pre-trade party decode failed"
[ "$A0_PERS" != "$B1_PERS" ] || fail "fixture parties not distinguishable"
note "oracle: join gives $A0_PERS (species $A0_SPEC), host gives $B1_PERS (species $B1_SPEC)"

run_instance() { # $1=name $2=save $3=script $4... extra args
  local name="$1" save="$2" script="$3"; shift 3
  SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy \
  timeout "$TIMEOUT_S" "$BIN" \
    --rom "$ROM" --bios-dir "$BIOS_DIR" --save "$save" \
    --log "$ART/$name.log" --dump-dir "$ART/${name}d" \
    --script "$script" \
    --option gpsp_serial=auto \
    --nick "$name" --net-loss "$LOSS" --net-jitter "$JITTER" \
    "$@" >"$ART/$name.stdout" 2>&1
  echo $? > "$ART/$name.rc"
}

echo "$MODE: port=$PORT loss=${LOSS}% jitter=${JITTER}ms"
run_instance host "$ART/host.sav" "$HOST_SCRIPT" --host "$PORT" &
HOST_JOB=$!
sleep 10
run_instance join "$ART/join.sav" "$FIX/emerald_trade_join.inputs" \
  --join "127.0.0.1:$PORT" &
JOIN_JOB=$!

if [ "$MODE" = "tradedisc" ]; then
  # Kill the joiner mid trade animation, once it reports trade_anim.
  DEADLINE=$(( $(date +%s) + TIMEOUT_S ))
  while [ "$(date +%s)" -lt "$DEADLINE" ]; do
    if grep -q "ap_mark text=trade_anim" "$ART/join.log" 2>/dev/null; then
      sleep 8
      JOIN_PIDS=$(pgrep -f "gpsp_sdl.*nick join")
      [ -n "${JOIN_PIDS:-}" ] && kill -9 $JOIN_PIDS 2>/dev/null         && note "joiner killed mid-trade (pid $JOIN_PIDS)"
      break
    fi
    sleep 1
  done
fi

wait "$HOST_JOB" "$JOIN_JOB" 2>/dev/null || true
HL="$ART/host.log"; JL="$ART/join.log"
[ -f "$HL" ] || fail "host log missing"
[ -f "$JL" ] || fail "join log missing"

# --- assertions common to both modes ----------------------------------------
grep -q "^EVT session_start id=0 " "$HL" || fail "host: no session_start id=0"
grep -Eq "^EVT session_start id=[1-4]" "$JL" || fail "join: no session_start"
grep -Eq "^EVT peer_connected id=[1-4]" "$HL" || fail "host: no peer_connected"
grep -q "^EVT peer_connected id=0" "$JL" || fail "join: never saw host"
for s in host join; do
  grep -q "ap_mark text=in_union_room" "$ART/$s.log" || fail "$s: never entered Union Room"
done
grep -q "ap_mark text=registered" "$HL" || fail "host: trading-board registration missing"
grep -q "ap_mark text=trade_anim" "$HL" || fail "host: trade never started"
grep -q "ap_mark text=trade_anim" "$JL" || fail "join: trade never started"

# driver health under impairment: the RELIABLE contract must hold.
for s in host join; do
  LAST=$(grep "^EVT net_stats" "$ART/$s.log" | tail -1)
  [ -n "$LAST" ] || fail "$s: no net_stats"
  echo "$s final: $LAST" >>"$ART/verdict.txt"
  echo "$LAST" | grep -Eq " overflow=0 " || fail "$s: reliable payloads dropped (overflow)"
  echo "$LAST" | grep -Eq "drop_crc=0 drop_mal=0" || fail "$s: malformed frames counted"
  ACKED=$(echo "$LAST" | sed -n 's/.* acked=\([0-9]*\).*/\1/p')
  [ "${ACKED:-0}" -gt 0 ] || fail "$s: nothing ever ACKed"
done

if [ "$MODE" = "tradedisc" ]; then
  # --- disconnect mode: the host must survive with the game's own dialog ----
  [ "$(cat "$ART/host.rc")" = "0" ] || fail "host crashed/hung (rc=$(cat "$ART/host.rc"))"
  grep -q "^EVT exit code=0" "$HL" || fail "host: no clean EVT exit"
  grep -q "ap_mark text=host_error_dialog" "$HL" \
    || fail "host: game error dialog never appeared"
  grep -q "ap_mark text=disc_done" "$HL" || fail "host: disc script incomplete"
  ls "$ART/hostd"/frame_*.bmp >/dev/null 2>&1 || fail "host: no error screenshot"
  note "PASS (--disconnect): joiner killed mid-trade; host survived with the"
  note "game's own communication-error dialog (screenshots in hostd/), clean exit"
  exit 0
fi

# --- normal mode: completion + oracle ---------------------------------------
[ "$(cat "$ART/host.rc")" = "0" ] || fail "host exit rc=$(cat "$ART/host.rc")"
[ "$(cat "$ART/join.rc")" = "0" ] || fail "join exit rc=$(cat "$ART/join.rc")"
grep -q "^EVT exit code=0" "$HL" || fail "host: no clean EVT exit"
grep -q "^EVT exit code=0" "$JL" || fail "join: no clean EVT exit"
grep -q "ap_mark text=trade_complete" "$HL" || fail "host: no trade_complete"
grep -q "ap_mark text=trade_complete" "$JL" || fail "join: no trade_complete"
grep -q "ap_done" "$HL" || fail "host: script did not finish"
grep -q "ap_done" "$JL" || fail "join: script did not finish"

val() { grep "ap_val name=$2 " "$1" | tail -1 | sed -n 's/.*val=\(0x[0-9a-f]*\).*/\1/p'; }
H_PRE0=$(val "$HL" pre0);  H_PRE1=$(val "$HL" pre1)
H_POST0=$(val "$HL" post0); H_POST1=$(val "$HL" post1)
J_PRE0=$(val "$JL" pre0);  J_PRE1=$(val "$JL" pre1)
J_POST0=$(val "$JL" post0); J_POST1=$(val "$JL" post1)
note "host pre=($H_PRE0,$H_PRE1) post=($H_POST0,$H_POST1)"
note "join pre=($J_PRE0,$J_PRE1) post=($J_POST0,$J_POST1)"

# RAM oracle: the two slot personalities swapped across the link.
[ "$H_POST1" = "$J_PRE0" ] || fail "oracle: host slot2 != join's offered mon"
[ "$H_POST1" != "$H_PRE1" ] || fail "oracle: host slot2 unchanged"
[ "$H_POST0" = "$H_PRE0" ] || fail "oracle: host slot1 should be untouched"
[ "$J_POST0" = "$H_PRE1" ] || fail "oracle: join slot1 != host's registered mon"
[ "$J_POST0" != "$J_PRE0" ] || fail "oracle: join slot1 unchanged"
[ "$J_POST1" = "$J_PRE1" ] || fail "oracle: join slot2 should be untouched"

# both ended back on the Union Room map
[ "$(val "$HL" end_loc)" = "0x00003c19" ] || fail "host: not in Union Room at end"
[ "$(val "$JL" end_loc)" = "0x00003c19" ] || fail "join: not in Union Room at end"

# post-trade in-game save flushed on both sides (the wireless trade's own
# save): sram_flush events strictly after the trade began.
for s in host join; do
  awk '/ap_mark text=trade_anim/{t=1} t && /^EVT sram_flush/{n++} END{exit n<1}' \
      "$ART/$s.log" || fail "$s: no post-trade sram_flush"
done

# Disk oracle: the SAVED game on each side contains the received mon.
python3 "$SCRIPT_DIR/read_party.py" "$ART/host.sav" >"$ART/post_host.txt" \
  || fail "post host save unreadable"
python3 "$SCRIPT_DIR/read_party.py" "$ART/join.sav" >"$ART/post_join.txt" \
  || fail "post join save unreadable"
grep -q "slot=1 personality=$A0_PERS .*species=$A0_SPEC" "$ART/post_host.txt" \
  || fail "host .sav: received mon not in saved party slot 2"
grep -q "slot=0 personality=$B1_PERS .*species=$B1_SPEC" "$ART/post_join.txt" \
  || fail "join .sav: received mon not in saved party slot 1"

ls "$ART/hostd"/frame_*.bmp >/dev/null 2>&1 || fail "host: no screenshots"
ls "$ART/joind"/frame_*.bmp >/dev/null 2>&1 || fail "join: no screenshots"

note "PASS: autonomous Union Room trade completed over netdrv UDP under"
note "${LOSS}% loss + ${JITTER}ms jitter; mons swapped and saved on both sides"
exit 0
