#!/usr/bin/env bash
# run_trade_test_psp.sh — Gate 4-E trade leg: an autonomous Union Room trade
# between TWO PPSSPP instances running our PSP EBOOT over the sceNetAdhoc PDP
# transport (netdrv on both sides).  This is the PSP port of run_trade_test.sh
# (Gate 3): same parked fixtures, same trade input scripts, same oracle — only
# the rig changes (PPSSPP multi-instance recipe from docs/TESTING.md instead of
# two desktop twins; no fault shim — PPSSPP localhost is the transport,
# impairment testing stayed at Gate 3).
#
# CROSS-EDITION (Phase 4).  `--roms=HOST,JOIN` picks the game on each side
# from {emerald, firered, leafgreen}; the default is emerald,emerald, which is
# the Gate-4 leg and behaves exactly as before.  Everything that differs per
# edition — ROM file, parked-save fixture, trade input script, the Union Room
# map id asserted at the end, and the .sav party layout the oracle decodes —
# comes out of the small table below, so adding a leg is data, not code.
#
#   ./run_trade_test_psp.sh                          # Emerald <-> Emerald
#   ./run_trade_test_psp.sh --roms=firered,leafgreen --radio=40
#   ./run_trade_test_psp.sh --roms=firered,emerald
#
# FR/LG parked saves are NOT generated by this repo: unlike Emerald there is
# no user save to clone from, and playing a new game to a wireless counter is
# a long scripted route we deliberately do not own (see docs/AUTOPILOT.md).
# Drop user-supplied saves in as testdata/fixtures/<edition>_parked.sav (or
# _parkedA/_parkedB for a same-edition pair) and the leg runs; the fixture
# contract they have to satisfy is documented at the top of
# testdata/fixtures/frlg_trade_host.inputs.
#
# Normal mode:
#   inst1 = HOST (CLONEB parked save, emerald_trade_host.inputs, hosts the
#           built-in AdhocServer + the netdrv session via .gpsp-harness.ini
#           host=1), registers slot-2 Magcargo requesting DRAGON.
#   inst2 = JOIN (AUSTIN parked save, emerald_trade_join.inputs, join=1),
#           offers slot-1 Salamence at the trading board.
#   Oracle (both sides, RAM + disk): party personalities swap exactly,
#   post-trade sram_flush, end map == Union Room, session_start +
#   peer_connected, driver health (overflow=0 drop_crc=0 drop_mal=0,
#   acked>0), clean EVT exits, screenshots.
#
# --disconnect mode:
#   HOST runs emerald_trade_host_disc.inputs; the harness SIGKILLs the
#   join *PPSSPP process* 8 s after it logs `ap_mark text=trade_anim`.
#   Asserts the host survives with the game's own communication-error
#   dialog, exits cleanly, no save damage.
#
# Fixtures regenerated via make_trade_fixtures.sh (desktop) when missing.
# Exit 0 = pass.  Artifacts in tools/e2e/artifacts/psptrade[disc]-<ts>/.
# Run inside WSL/Linux.  Prereqs: setup_ppsspp.sh ran once; psp/EBOOT.PBP.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Serialise against every other ad-hoc test on this machine.  PPSSPP's
# AdhocServer port and /dev/shm/PPSSPP_ID are global, so SANDBOX_ROOT does
# NOT make two concurrent runs independent -- they corrupt each other and
# the symptom looks like a transport regression.  See adhoc_lock.sh.
. "$SCRIPT_DIR/adhoc_lock.sh"; adhoc_lock
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
PPSSPP_DIR="${PPSSPP_DIR:-$HOME/ppsspp}"
SANDBOX_ROOT="${SANDBOX_ROOT:-$HOME/gpsp-e2e/sandboxes}"
TIMEOUT_S="${TIMEOUT_S:-900}"

EBOOT="$REPO/psp/EBOOT.PBP"
BIOS="$REPO/testdata/gba_bios.bin"
FIX="$REPO/testdata/fixtures"

# --- per-edition table -------------------------------------------------------
# rom file | header game code | header revision (0xBC) | trade scripts |
# Union Room map id (SaveBlock1.location as mapGroup|mapNum<<8) | .sav layout
ed_rom() { case "$1" in
  emerald)   echo "$REPO/testdata/Pokemon - Emerald Version (USA, Europe).gba" ;;
  firered)   echo "$REPO/testdata/Pokemon - FireRed Version (USA, Europe) (Rev 1).gba" ;;
  leafgreen) echo "$REPO/testdata/Pokemon - LeafGreen Version (USA, Europe) (Rev 1).gba" ;;
esac; }
ed_code() { case "$1" in emerald) echo BPEE ;; firered) echo BPRE ;; leafgreen) echo BPGE ;; esac; }
ed_rev()  { case "$1" in emerald) echo 00 ;; *) echo 01 ;; esac; }
ed_host_script() { case "$1" in emerald) echo emerald_trade_host.inputs ;; *) echo frlg_trade_host.inputs ;; esac; }
ed_join_script() { case "$1" in emerald) echo emerald_trade_join.inputs ;; *) echo frlg_trade_join.inputs ;; esac; }
ed_uroom() { case "$1" in emerald) echo 0x00003c19 ;; *) echo 0x00000400 ;; esac; }
ed_savegame() { case "$1" in emerald) echo emerald ;; *) echo frlg ;; esac; }

MODE=psptrade
RADIO=""            # "", "40" or "80" — emulated ad-hoc RTT profile
HOST_ED=emerald
JOIN_ED=emerald
SLOW_JOIN_US=0      # ADR-0027: burn N us/frame on the JOIN instance only
PACE_MATCH=""       # "", "0" off, "1" fixed-rate (ADR-0033), "2" adaptive
SESSION_FPS=""      # ADR-0033: pin net_session_fps (decimal fps)
# ADR-0037: pin net_frameskip.  1 = adaptive, which is the policy whose
# thresholds used to be absolute constants.  Combined with a --session-fps
# clamp this reproduces the field bug on the rig: the OLD code engages
# fixed_interval within ~3 s of the clamp taking hold and never releases.
NET_FRAMESKIP=""
RFU_RX_CAP=""
for arg in "$@"; do
  case "$arg" in
    --disconnect)  MODE=psptradedisc ;;
    --radio=40)    RADIO=40 ;;
    --radio=80)    RADIO=80 ;;
    --radio=160)   RADIO=160 ;;
    --slow-join=*) SLOW_JOIN_US="${arg#--slow-join=}" ;;
    --pace-match=*) PACE_MATCH="${arg#--pace-match=}" ;;
    --session-fps=*) SESSION_FPS="${arg#--session-fps=}" ;;
    --net-frameskip=*) NET_FRAMESKIP="${arg#--net-frameskip=}" ;;
    --rfu-rx-cap=*)    RFU_RX_CAP="${arg#--rfu-rx-cap=}" ;;
    --roms=*)      HOST_ED="${arg#--roms=}"; JOIN_ED="${HOST_ED#*,}"; HOST_ED="${HOST_ED%%,*}" ;;
    *) echo "usage: $0 [--disconnect] [--radio=40|80|160] [--roms=HOST,JOIN]" >&2
       echo "                [--slow-join=US] [--pace-match=0|1]" >&2
       echo "       editions: emerald firered leafgreen" >&2
       echo "       --slow-join=US  burn US microseconds of busy work per frame" >&2
       echo "                       on the JOIN instance only (ADR-0027).  The rig" >&2
       echo "                       runs both instances at full speed, so without" >&2
       echo "                       this the field's host/join asymmetry does not" >&2
       echo "                       exist here and pace matching never engages." >&2
       echo "                       6000 walks the join from ~59 down past the" >&2
       echo "                       40 fps floor, so one run exercises engage," >&2
       echo "                       ramp, floor and clean release." >&2
       echo "       --pace-match=N  pin net_pace_match: 0 off, 1 fixed-rate" >&2
       echo "                       (ADR-0033 default), 2 the ADR-0027/0028" >&2
       echo "                       adaptive matcher.  NOTE 1 CHANGED MEANING." >&2
       echo "       --rfu-rx-cap=N     ADR-0042 per-frame RFU delivery cap on the" >&2
       echo "                          JOINING side (0 = off = default path)." >&2
       echo "       --net-frameskip=N  pin net_frameskip: 0 off, 1 adaptive," >&2
       echo "                       2 auto.  With --session-fps this is the" >&2
       echo "                       ADR-0037 regression case." >&2
       echo "       --session-fps=F pin net_session_fps (mode 1 clamp, e.g." >&2
       echo "                       40.00).  Both instances get the same value;" >&2
       echo "                       the gate asserts they announce it identically." >&2
       exit 2 ;;
  esac
done
case "$SLOW_JOIN_US" in *[!0-9]*) echo "--slow-join wants microseconds" >&2; exit 2 ;; esac
for ed in "$HOST_ED" "$JOIN_ED"; do
  case "$ed" in emerald|firered|leafgreen) ;;
    *) echo "unknown edition '$ed' (emerald|firered|leafgreen)" >&2; exit 2 ;;
  esac
done

# Emulated real-radio profile (docs/HANDOFF.md issue #2): PPSSPP's AdhocServer
# loopback RTT is microseconds, real PSP ad-hoc is tens of ms — the gap is
# exactly why the ARQ storm never showed up in the harness.  Each side delays
# its OWN receive path, so RTT = 2 x latency (+ jitter).
#   --radio=160 is the QUEUE-STALL stress profile, not a plausible radio: at a
#   160 ms RTT a 16-deep send window sustains only ~100 payload/s against the
#   core's ~120/s active-link demand, so the tx queue grows without bound —
#   which is precisely the field's step 3->4 (window stalls awaiting acks, ring
#   backs up, RELIABLE payload discarded, RFU state destroyed, game shows a
#   communication error).  It is the harness reproduction of the kill shot.
case "$RADIO" in
  40)  LAT_MS=20; JIT_MS=10; TAG="${MODE}r40" ;;
  80)  LAT_MS=40; JIT_MS=15; TAG="${MODE}r80" ;;
  160) LAT_MS=80; JIT_MS=20; TAG="${MODE}r160" ;;
  *)   LAT_MS=0;  JIT_MS=0;  TAG="$MODE" ;;
esac
[ "$HOST_ED" = emerald ] && [ "$JOIN_ED" = emerald ] || TAG="$TAG-${HOST_ED:0:2}${JOIN_ED:0:2}"

ART="$SCRIPT_DIR/artifacts/$TAG-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$ART"

fail() { echo "FAIL: $*" | tee -a "$ART/verdict.txt"; exit 1; }
note() { echo "$*" | tee -a "$ART/verdict.txt"; }

[ -x "$PPSSPP_DIR/build/PPSSPPSDL" ] || fail "PPSSPPSDL not built (run setup_ppsspp.sh)"
[ -f "$EBOOT" ] || fail "psp/EBOOT.PBP missing (build it: see psp/Makefile header)"
[ -f "$BIOS" ]  || fail "gba_bios.bin missing"

HOST_ROM="$(ed_rom "$HOST_ED")"; JOIN_ROM="$(ed_rom "$JOIN_ED")"

# --- ROM identity: game code (0xAC) AND revision byte (0xBC) ----------------
# ADR-0009 pins the canonical images: Emerald is retail **rev 0**, FR/LG are
# **rev 1**.  The autopilot address tables are per-revision constants, so a
# silently-swapped image would show up as a mystifying predicate timeout
# hundreds of frames in.  Check it here instead.
check_rom() { # $1=edition $2=path
  [ -f "$2" ] || fail "$1: ROM missing ($2)"
  local code rev
  code=$(dd if="$2" bs=1 skip=172 count=4 2>/dev/null)
  rev=$(dd if="$2" bs=1 skip=188 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n')
  [ "$code" = "$(ed_code "$1")" ] || fail "$1: header game code is '$code', expected $(ed_code "$1")"
  [ "$rev" = "$(ed_rev "$1")" ] || fail "$1: header revision is 0x$rev, expected 0x$(ed_rev "$1")"
  note "$1 ROM ok: code=$code rev=0x$rev"
}
check_rom "$HOST_ED" "$HOST_ROM"
check_rom "$JOIN_ED" "$JOIN_ROM"

# --- parked fixtures --------------------------------------------------------
# Emerald's are generated from the user's own save (make_trade_fixtures.sh).
# FR/LG's are supplied by hand — see the header of this file.
fixture_for() { # $1=edition $2=A|B  -> path, or empty
  local p="$FIX/$1_parked$2.sav"
  [ -f "$p" ] || p="$FIX/$1_parked.sav"
  [ -f "$p" ] && echo "$p"
}
if [ "$HOST_ED" = emerald ] || [ "$JOIN_ED" = emerald ]; then
  if [ ! -f "$FIX/emerald_parkedA.sav" ] || [ ! -f "$FIX/emerald_parkedB.sav" ]; then
    note "emerald parked fixtures missing — generating (make_trade_fixtures.sh)"
    bash "$SCRIPT_DIR/make_trade_fixtures.sh" || fail "fixture generation failed"
  fi
fi
HOST_SAV="$(fixture_for "$HOST_ED" B)"
JOIN_SAV="$(fixture_for "$JOIN_ED" A)"
[ -n "$HOST_SAV" ] || fail "host: no parked save for $HOST_ED — drop one in as $FIX/${HOST_ED}_parked.sav (contract: testdata/fixtures/frlg_trade_host.inputs header)"
[ -n "$JOIN_SAV" ] || fail "join: no parked save for $JOIN_ED — drop one in as $FIX/${JOIN_ED}_parked.sav (contract: testdata/fixtures/frlg_trade_host.inputs header)"
[ "$HOST_SAV" != "$JOIN_SAV" ] || fail "host and join would share one save file ($HOST_SAV); a same-edition leg needs _parkedA.sav and _parkedB.sav"
note "leg: host=$HOST_ED($(basename "$HOST_SAV")) join=$JOIN_ED($(basename "$JOIN_SAV"))"

HOST_SCRIPT="$(ed_host_script "$HOST_ED")"
JOIN_SCRIPT="$(ed_join_script "$JOIN_ED")"
if [ "$MODE" = "psptradedisc" ]; then
  [ "$HOST_ED" = emerald ] \
    || fail "--disconnect only has a host script for emerald (emerald_trade_host_disc.inputs)"
  HOST_SCRIPT="emerald_trade_host_disc.inputs"
fi

# Pre-trade identities (oracle inputs) — same as the desktop harness.
python3 "$SCRIPT_DIR/read_party.py" "$HOST_SAV" --game="$(ed_savegame "$HOST_ED")" >"$ART/pre_host.txt" \
  || fail "cannot decode host parked save"
python3 "$SCRIPT_DIR/read_party.py" "$JOIN_SAV" --game="$(ed_savegame "$JOIN_ED")" >"$ART/pre_join.txt" \
  || fail "cannot decode join parked save"
A0_PERS=$(awk '/^mon slot=0 /{print $3}' "$ART/pre_join.txt" | cut -d= -f2)
A0_SPEC=$(awk '/^mon slot=0 /{print $5}' "$ART/pre_join.txt" | cut -d= -f2)
B1_PERS=$(awk '/^mon slot=1 /{print $3}' "$ART/pre_host.txt" | cut -d= -f2)
B1_SPEC=$(awk '/^mon slot=1 /{print $5}' "$ART/pre_host.txt" | cut -d= -f2)
[ -n "$A0_PERS" ] && [ -n "$B1_PERS" ] || fail "pre-trade party decode failed"
[ -z "$RADIO" ] || note "radio profile: ${LAT_MS}ms/side + ${JIT_MS}ms jitter (~$((LAT_MS*2))ms RTT)"
[ "$A0_PERS" != "$B1_PERS" ] || fail "fixture parties not distinguishable"
note "oracle: join gives $A0_PERS (species $A0_SPEC), host gives $B1_PERS (species $B1_SPEC)"

# --- 1. Fresh 2-instance sandboxes (server on inst1, TESTING.md §2-4) --------
"$SCRIPT_DIR/setup_ppsspp.sh" --instances 2 --skip-build >/dev/null \
  || fail "setup_ppsspp.sh sandbox creation failed"

setup_inst() { # $1=inst# $2=role(host|join) $3=save $4=script $5=nick $6=rom
               # $7=pace_slow_us for THIS instance (ADR-0027, 0 = normal)
  local GAME="$SANDBOX_ROOT/inst$1/ppsspp/PSP/GAME/gpsp-adhoc"
  mkdir -p "$GAME/roms" "$GAME/log"
  cp "$EBOOT" "$GAME/EBOOT.PBP"
  cp "$BIOS"  "$GAME/gba_bios.bin"
  # the on-card names stay emerald.gba/.sav whatever the edition — the EBOOT
  # picks the first ROM in roms/ and the .sav has to sit beside it.
  cp "$6"     "$GAME/roms/emerald.gba"
  cp "$3"     "$GAME/roms/emerald.sav"
  cp "$FIX/$4" "$GAME/$4"
  cat > "$GAME/.gpsp-harness.ini" <<EOF
script = $4
$2 = 1
nick = $5
net_latency_ms = $LAT_MS
net_jitter_ms = $JIT_MS
pace_slow_us = ${7:-0}
EOF
  [ -n "$PACE_MATCH" ] && echo "net_pace_match = $PACE_MATCH" >> "$GAME/.gpsp-harness.ini"
  [ -n "$SESSION_FPS" ] && echo "net_session_fps = $SESSION_FPS" >> "$GAME/.gpsp-harness.ini"
  [ -n "$NET_FRAMESKIP" ] && echo "net_frameskip = $NET_FRAMESKIP" >> "$GAME/.gpsp-harness.ini"
  # ADR-0042 is a CLIENT-side knob: rfu.c only consults it in RFU_STATE_CLIENT.
  # Setting it host-side would be inert and would make the log misleading.
  if [ -n "$RFU_RX_CAP" ] && [ "$2" = "join" ]; then
    echo "rfu_rx_cap = $RFU_RX_CAP" >> "$GAME/.gpsp-harness.ini"
  fi
  return 0
}
setup_inst 1 host "$HOST_SAV" "$HOST_SCRIPT" host "$HOST_ROM" 0
setup_inst 2 join "$JOIN_SAV" "$JOIN_SCRIPT" join "$JOIN_ROM" "$SLOW_JOIN_US"

G1="$SANDBOX_ROOT/inst1/ppsspp/PSP/GAME/gpsp-adhoc"
G2="$SANDBOX_ROOT/inst2/ppsspp/PSP/GAME/gpsp-adhoc"
HL="$G1/log/frontend.log"; JL="$G2/log/frontend.log"

# --- 2. Launch (inst1 first: PPSSPP_ID=1 + built-in AdhocServer) -------------
rm -f /dev/shm/PPSSPP_ID
launch() { # $1 = instance number.  Redirection on the SUBSHELL, not the
  # inner command — else the $(launch N) capture pipe stays open and the
  # command substitution blocks until the emulator exits.
  ( cd "$PPSSPP_DIR/build" && \
    XDG_CONFIG_HOME="$SANDBOX_ROOT/inst$1" SDL_AUDIODRIVER=dummy LIBGL_ALWAYS_SOFTWARE=1 \
    timeout $((TIMEOUT_S + 60)) xvfb-run -a -s "-screen 0 1280x720x24 +extension GLX +render -noreset" \
      ./PPSSPPSDL --windowed \
      "$SANDBOX_ROOT/inst$1/ppsspp/PSP/GAME/gpsp-adhoc/EBOOT.PBP" \
  ) >"$ART/inst$1.emu.log" 2>&1 &
  echo $!
}
PID1=$(launch 1)
# Gate on inst1's adhoc_up EVT (group registered at the built-in
# AdhocServer); first boot in a fresh sandbox can take >60 s before the
# EBOOT even runs (Vulkan/llvmpipe warmup).
SRV_OK=0
for _ in $(seq 1 180); do
  if grep -q "^EVT adhoc_up" "$HL" 2>/dev/null; then SRV_OK=1; break; fi
  grep -q "^EVT net_error" "$HL" 2>/dev/null && break
  kill -0 "$PID1" 2>/dev/null || break
  sleep 1
done
[ "$SRV_OK" -eq 1 ] || { cp "$HL" "$ART/host.log" 2>/dev/null; \
  fail "inst1 adhoc bring-up never completed (no adhoc_up; see host.log/inst1.emu.log)"; }
PID2=$(launch 2)

# --- 3. Wait / disconnect choreography ---------------------------------------
if [ "$MODE" = "psptradedisc" ]; then
  DEADLINE=$(( $(date +%s) + TIMEOUT_S ))
  KILLED=0
  while [ "$(date +%s)" -lt "$DEADLINE" ]; do
    if grep -q "ap_mark text=trade_anim" "$JL" 2>/dev/null; then
      sleep 8
      pkill -9 -f "$SANDBOX_ROOT/inst2/ppsspp/PSP/GAME/gpsp-adhoc/EBOOT.PBP" 2>/dev/null \
        && { KILLED=1; note "join PPSSPP instance killed mid-trade"; }
      break
    fi
    kill -0 "$PID1" 2>/dev/null || break
    sleep 1
  done
  [ "$KILLED" = 1 ] || fail "join never reached trade_anim (nothing to kill)"
fi

for _ in $(seq 1 "$TIMEOUT_S"); do
  if [ "$MODE" = "psptradedisc" ]; then
    grep -q "^EVT exit code=" "$HL" 2>/dev/null && break
    kill -0 "$PID1" 2>/dev/null || break
  else
    D1=0; D2=0
    grep -q "^EVT exit code=" "$HL" 2>/dev/null && D1=1
    grep -q "^EVT exit code=" "$JL" 2>/dev/null && D2=1
    [ "$D1" = 1 ] && [ "$D2" = 1 ] && break
    if ! kill -0 "$PID1" 2>/dev/null && ! kill -0 "$PID2" 2>/dev/null; then break; fi
  fi
  sleep 1
done
sleep 1
pkill -9 -f "$SANDBOX_ROOT/inst" 2>/dev/null || true
wait "$PID1" "$PID2" 2>/dev/null || true

cp "$HL" "$ART/host.log" 2>/dev/null || true
cp "$JL" "$ART/join.log" 2>/dev/null || true
mkdir -p "$ART/hostd" "$ART/joind"
cp "$G1"/log/frame_*.bmp "$ART/hostd/" 2>/dev/null || true
cp "$G2"/log/frame_*.bmp "$ART/joind/" 2>/dev/null || true
cp "$G1/roms/emerald.sav" "$ART/host.sav" 2>/dev/null || true
cp "$G2/roms/emerald.sav" "$ART/join.sav" 2>/dev/null || true
HL="$ART/host.log"; JL="$ART/join.log"
[ -f "$HL" ] || fail "host log missing"
[ -f "$JL" ] || fail "join log missing"

# --- 4. Assertions common to both modes (mirrors run_trade_test.sh) ----------
grep -q "^EVT adhoc_up group=GPSP07" "$HL" || fail "host: adhoc bring-up failed"
grep -q "^EVT adhoc_up group=GPSP07" "$JL" || fail "join: adhoc bring-up failed"
grep -q "^EVT session_start id=0 " "$HL" || fail "host: no session_start id=0"
grep -Eq "^EVT session_start id=[1-4]" "$JL" || fail "join: no session_start"
grep -Eq "^EVT peer_connected id=[1-4]" "$HL" || fail "host: no peer_connected"
grep -q "^EVT peer_connected id=0" "$JL" || fail "join: never saw host"
for s in host join; do
  grep -q "ap_mark text=in_union_room" "$ART/$s.log" || fail "$s: never entered Union Room"
done
grep -q "ap_mark text=registered" "$HL" || fail "host: trading-board registration missing"
grep -q "ap_mark text=trade_anim" "$HL" || fail "host: trade never started"
grep -q "ap_mark text=trade_anim" "$JL" || fail "join: trade never started"

# driver health: the RELIABLE contract must hold on the PDP transport too.
for s in host join; do
  LAST=$(grep "^EVT net_stats" "$ART/$s.log" | tail -1)
  [ -n "$LAST" ] || fail "$s: no net_stats"
  note "$s final: $LAST"
  echo "$LAST" | grep -Eq " overflow=0 " || fail "$s: reliable payloads dropped (overflow)"
  echo "$LAST" | grep -Eq "drop_crc=0 drop_mal=0" || fail "$s: malformed frames counted"
  ACKED=$(echo "$LAST" | sed -n 's/.* acked=\([0-9]*\).*/\1/p')
  [ "${ACKED:-0}" -gt 0 ] || fail "$s: nothing ever ACKed"
  # ARQ storm guard (HANDOFF issue #2): the field failure ran retx/acked ~2.8.
  # Adaptive RTO must keep it near the loopback baseline even at radio RTT.
  RETX=$(echo "$LAST" | sed -n 's/.* retx=\([0-9]*\).*/\1/p')
  RATIO=$(( (${RETX:-0} * 100) / ACKED ))
  note "$s retx/acked = ${RATIO}% (retx=$RETX acked=$ACKED)"
  [ "$RATIO" -le 60 ] || fail "$s: ARQ retransmit storm (retx/acked=${RATIO}%, expect <=60%)"
  note "$s adhoc: $(grep '^EVT adhoc_stats' "$ART/$s.log" | tail -1)"
  # ADR-0028 inserted corewin=/corespike= between core= and pace=, so match
  # each field on its own rather than assuming they stay adjacent.
  note "$s core/pace: $(grep '^EVT sess_cost' "$ART/$s.log" | tail -1 \
        | grep -oE 'core=[^ ]+|corewin=[^ ]+|corespike=[^ ]+|pace=[^ ]+' | tr '\n' ' ')"
  note "$s core_prof: $(grep '^EVT core_prof' "$ART/$s.log" | tail -1)"
done

# --- session pacing (ADR-0033 fixed-rate / ADR-0027 adaptive) ---------------
# THE RIG RUNS BOTH INSTANCES AT FULL SPEED, so it does NOT reproduce the
# field's host/join asymmetry (the join console's extra cost is inside the
# core's RFU client path — see ADR-0028).  What the rig CAN prove is that the
# selected policy comes up, applies, and is symmetric.
for s in host join; do
  grep -q "^EVT net_pace_match mode=" "$ART/$s.log" \
    || fail "$s: pace policy never reported"
done
PACE_MODE=$(grep -h '^EVT net_pace_match mode=' "$HL" | tail -1 \
            | sed -n 's/.*mode=\([0-9]*\).*/\1/p')
note "pace policy mode=$PACE_MODE"

# ADR-0035: the struct-layout corruption guard.  `EVT config_corrupt` means a
# field held a value outside its own enum range at save time — memory was
# wrong, not the file.  It shipped once (blit_mode = 1347637319, the ASCII
# "GPSP" of a room code written four bytes early by a stale ui_psp.o); it must
# never ship again, and unlike most guards this one has to be checked in the
# TRADE test because the wireless UI is what writes `group`.
for s in host join; do
  if grep -q "^EVT config_corrupt " "$ART/$s.log"; then
    grep "^EVT config_corrupt " "$ART/$s.log" | head -5 | tee -a "$ART/verdict.txt"
    fail "$s: config memory corrupt — stale object or overrun (ADR-0035)"
  fi
done
note "config_corrupt: none on either side"
if [ "${PACE_MODE:-1}" = "1" ]; then
  # FIXED-RATE (ADR-0033).  Unlike the adaptive matcher this is NOT inert on
  # symmetric peers — that is the whole point, so the rig exercises it fully:
  # both sides must announce the SAME clamp and both must actually reach it.
  FIXED_H="" ; FIXED_J=""
  for s in host join; do
    grep -q "^EVT session_pace .* reason=session_start" "$ART/$s.log" \
      || fail "$s: fixed-rate clamp never announced (ADR-0033)"
    grep -q "^EVT session_pace .* reason=session_end" "$ART/$s.log" \
      || fail "$s: clamp never released at teardown (ADR-0033)"
    grep -qE "^EVT session_pace .* reason=ramp_done([ 	]|$)" "$ART/$s.log" \
      || fail "$s: the glide into the clamp never completed (ADR-0033)"
  done
  FIXED_H=$(grep '^EVT session_pace .* reason=session_start' "$HL" | tail -1 \
            | sed -n 's/.*fps=\([0-9.]*\).*/\1/p')
  FIXED_J=$(grep '^EVT session_pace .* reason=session_start' "$JL" | tail -1 \
            | sed -n 's/.*fps=\([0-9.]*\).*/\1/p')
  # Determinism is the entire claim: no negotiation, so the two constants must
  # be bit-identical.  A mismatch here means one side read a different config.
  [ -n "$FIXED_H" ] && [ "$FIXED_H" = "$FIXED_J" ] \
    || fail "fixed rate differs between peers ($FIXED_H vs $FIXED_J) — ADR-0033"
  note "session_pace: both sides clamped to $FIXED_H fps, ramped in and out"
  # No control loop may run in this mode: pace_match lines belong to mode 2.
  for s in host join; do
    grep -q "^EVT pace_match " "$ART/$s.log" \
      && fail "$s: adaptive matcher ran in fixed mode (ADR-0033)"
  done
  # ADR-0035: the applied rate must be one the throttle can actually hold,
  # i.e. a whole-vblank divisor.  The field ran 35-38 fps against a 40.00
  # clamp because 40 is not one; this asserts we never ship that again.
  case "$FIXED_H" in
    59.94|29.97|19.98) note "clamp $FIXED_H fps is a whole-vblank rate (ADR-0035)" ;;
    *) if grep -q "net_session_fps_snap = 0" "$G1/.gpsp-harness.ini" 2>/dev/null; then
         note "clamp $FIXED_H is not a vblank divisor, but snapping is off for this A/B"
       else
         fail "clamp $FIXED_H fps is not 59.94/N — the snap did not fire (ADR-0035)"
       fi ;;
  esac
  # And the rate must actually be delivered.  A miss is a report, not a
  # failure (ADR-0033) — but it must never move the target, which is the
  # whole no-chase rule, so assert that rather than just noting the miss.
  for s in host join; do
    if grep -q "^EVT session_pace_miss " "$ART/$s.log"; then
      note "$s: WARNING $(grep '^EVT session_pace_miss' "$ART/$s.log" | tail -1)"
      LAST_T=$(grep '^EVT sess_cost' "$ART/$s.log" | tail -1 \
               | sed -n 's/.* pace=\([0-9.]*\)\/.*/\1/p')
      [ -z "$LAST_T" ] || [ "$LAST_T" = "$FIXED_H" ] \
        || fail "$s: target moved to $LAST_T after a miss — no-chase rule broke (ADR-0033)"
    fi
  done
elif [ "$SLOW_JOIN_US" -eq 0 ]; then
  for s in host join; do
    grep -q "^EVT pace_match .* engaged=1" "$ART/$s.log" \
      && fail "$s: paced down against a peer of equal speed (ADR-0027)"
  done
  note "pace_match: inert on symmetric peers, as intended"
else
  # A deliberately slowed join reproduces the field's role asymmetry.
  # Exactly ONE mover: the fast side (host) throttles, the slow side must not.
  grep -q "^EVT pace_match .* engaged=1" "$HL" \
    || fail "host: never paced down to the slowed join peer (ADR-0027)"
  grep -q "^EVT pace_match .* engaged=1" "$JL" \
    && fail "join: the SLOW side throttled too — both sides moved (ADR-0027)"
  note "pace_match host: $(grep '^EVT pace_match' "$HL" | tail -1)"
  note "pace_match join: $(grep -c '^EVT pace_match' "$JL") line(s), engaged=0"
  # Ratchet guard: self_cap is capability, so it must NOT sag while engaged.
  # If it does, the pair is chasing each other's throttled rate downward.
  CAP0=$(grep '^EVT pace_match' "$HL" | head -1 | sed -n 's/.* self_cap=\([0-9]*\)\..*/\1/p')
  CAPN=$(grep '^EVT pace_match' "$HL" | tail -1 | sed -n 's/.* self_cap=\([0-9]*\)\..*/\1/p')
  note "host self_cap: first=${CAP0:-?} last=${CAPN:-?} fps (must not sag)"
  [ $(( ${CAP0:-0} - ${CAPN:-0} )) -le 5 ] \
    || fail "host: self_cap sagged ${CAP0}->${CAPN} while pacing — RATCHET (ADR-0027)"
  # Floor: never chased below 40 fps.
  awk '/^EVT pace_match/ { for (i=1;i<=NF;i++) if ($i ~ /^target=/) {
         split($i,a,"="); if (a[2]+0 < 40.0) { print; exit 1 } } }' "$HL" \
    || fail "host: paced below the 40 fps floor (ADR-0027)"
fi

if [ "$MODE" = "psptradedisc" ]; then
  # --- disconnect: the host survives with the game's own error dialog -------
  grep -q "^EVT exit code=0" "$HL" || fail "host: no clean EVT exit"
  grep -q "ap_mark text=host_error_dialog" "$HL" \
    || fail "host: game error dialog never appeared"
  grep -q "ap_mark text=disc_done" "$HL" || fail "host: disc script incomplete"
  ls "$ART/hostd"/frame_*.bmp >/dev/null 2>&1 || fail "host: no error screenshot"
  note "PASS (--disconnect): join instance killed mid-trade; host survived with"
  note "the game's own communication-error dialog and a clean exit"
  exit 0
fi

# --- 5. Normal mode: completion + oracle -------------------------------------
grep -q "^EVT exit code=0" "$HL" || fail "host: no clean EVT exit"
grep -q "^EVT exit code=0" "$JL" || fail "join: no clean EVT exit"
grep -q "ap_mark text=trade_complete" "$HL" || fail "host: no trade_complete"
grep -q "ap_mark text=trade_complete" "$JL" || fail "join: no trade_complete"
grep -q "ap_done" "$HL" || fail "host: script did not finish"
grep -q "ap_done" "$JL" || fail "join: script did not finish"

val() { grep "ap_val name=$2 " "$1" | tail -1 | sed -n 's/.*val=\(0x[0-9a-f]*\).*/\1/p'; }
H_PRE0=$(val "$HL" pre0);  H_PRE1=$(val "$HL" pre1)
H_POST0=$(val "$HL" post0); H_POST1=$(val "$HL" post1)
J_PRE0=$(val "$JL" pre0);  J_PRE1=$(val "$JL" pre1)
J_POST0=$(val "$JL" post0); J_POST1=$(val "$JL" post1)
note "host pre=($H_PRE0,$H_PRE1) post=($H_POST0,$H_POST1)"
note "join pre=($J_PRE0,$J_PRE1) post=($J_POST0,$J_POST1)"

[ "$H_POST1" = "$J_PRE0" ] || fail "oracle: host slot2 != join's offered mon"
[ "$H_POST1" != "$H_PRE1" ] || fail "oracle: host slot2 unchanged"
[ "$H_POST0" = "$H_PRE0" ] || fail "oracle: host slot1 should be untouched"
[ "$J_POST0" = "$H_PRE1" ] || fail "oracle: join slot1 != host's registered mon"
[ "$J_POST0" != "$J_PRE0" ] || fail "oracle: join slot1 unchanged"
[ "$J_POST1" = "$J_PRE1" ] || fail "oracle: join slot2 should be untouched"

[ "$(val "$HL" end_loc)" = "$(ed_uroom "$HOST_ED")" ] || fail "host: not in Union Room at end"
[ "$(val "$JL" end_loc)" = "$(ed_uroom "$JOIN_ED")" ] || fail "join: not in Union Room at end"

for s in host join; do
  awk '/ap_mark text=trade_anim/{t=1} t && /^EVT sram_flush/{n++} END{exit n<1}' \
      "$ART/$s.log" || fail "$s: no post-trade sram_flush"
done

# Disk oracle: the SAVED game on each side contains the received mon.
python3 "$SCRIPT_DIR/read_party.py" "$ART/host.sav" --game="$(ed_savegame "$HOST_ED")" >"$ART/post_host.txt" \
  || fail "post host save unreadable"
python3 "$SCRIPT_DIR/read_party.py" "$ART/join.sav" --game="$(ed_savegame "$JOIN_ED")" >"$ART/post_join.txt" \
  || fail "post join save unreadable"
grep -q "slot=1 personality=$A0_PERS .*species=$A0_SPEC" "$ART/post_host.txt" \
  || fail "host .sav: received mon not in saved party slot 2"
grep -q "slot=0 personality=$B1_PERS .*species=$B1_SPEC" "$ART/post_join.txt" \
  || fail "join .sav: received mon not in saved party slot 1"

ls "$ART/hostd"/frame_*.bmp >/dev/null 2>&1 || fail "host: no screenshots"
ls "$ART/joind"/frame_*.bmp >/dev/null 2>&1 || fail "join: no screenshots"

note "PASS: autonomous Union Room trade completed between two PPSSPP instances"
note "over the sceNetAdhoc PDP transport; mons swapped and saved on both sides"
exit 0
