#!/usr/bin/env python3
"""gen_cgb_lcd_table.py -- write gbcore/tgbdual/_cgb_lcd_table.h.

    python tools/gen_cgb_lcd_table.py > gbcore/tgbdual/_cgb_lcd_table.h

The Game Boy Color's LCD does not show a CRAM value linearly: its response
curve lifts the mid-tones (a channel value of 16 of 31 is about 63 % of full
brightness, not 52 %), and its green sub-pixel picks up some of the blue.
Games were coloured on that screen, so a straight 5-to-8-bit expansion on a
modern (sRGB) display looks too dark and over-saturated -- docs/
GB-PALETTE-FIXES.md, "Crystal too dark".

The tables are SameBoy's measured CGB model (Core/display.c,
GB_convert_rgb15, mode GB_COLOR_CORRECTION_MODERN_BALANCED -- SameBoy's
default -- for a CGB, not an AGB; SameBoy is MIT/Expat licensed, Copyright
(c) 2015-2025 Lior Halphon):

    R = curve[r], B = curve[b]
    G = curve[g] if curve[g] == curve[b], else
        round((( (curve[g]/255)^1.6 * 3 + (curve[b]/255)^1.6 ) / 4)^(1/1.6) * 255)

Generated once and committed, so the core does no floating point and the
result does not depend on a libm: a palette entry converts with three table
reads, and only when the game rewrites it (gbc_recreate_colors).
"""
import sys

CURVE = [0, 6, 12, 20, 28, 36, 45, 56, 66, 76, 88, 100, 113, 125, 137, 149,
         161, 172, 182, 192, 202, 210, 218, 225, 232, 238, 243, 247, 250, 252,
         254, 255]
GAMMA = 1.6


def green(g5: int, b5: int) -> int:
    g, b = CURVE[g5], CURVE[b5]
    if g == b:
        return g
    v = ((g / 255.0) ** GAMMA * 3 + (b / 255.0) ** GAMMA) / 4
    # SameBoy: round(pow(v, 1/gamma) * 255), C round() = half away from zero
    x = v ** (1 / GAMMA) * 255
    return int(x + 0.5)


def main() -> None:
    out = []
    out.append("/* Generated by tools/gen_cgb_lcd_table.py -- do not edit.")
    out.append(" * Game Boy Color LCD colour model (SameBoy, MIT/Expat, Copyright (c)")
    out.append(" * 2015-2025 Lior Halphon; mode MODERN_BALANCED, CGB).  Defined once, in")
    out.append(" * tgb_shared.c, outside the per-instance partial link; lcd.c sees only")
    out.append(" * the declarations.  docs/GB-PALETTE-FIXES.md. */")
    out.append("#define _cgb_lcd_curve tgbshared_cgb_lcd_curve")
    out.append("#define _cgb_lcd_green tgbshared_cgb_lcd_green")
    out.append("#ifndef TGB_SHARED_TABLES")
    out.append("extern const unsigned char _cgb_lcd_curve[32];")
    out.append("extern const unsigned char _cgb_lcd_green[32 * 32];")
    out.append("#else")
    out.append("/* channel value 0..31 -> 8-bit display level (red and blue) */")
    out.append("const unsigned char _cgb_lcd_curve[32] = {")
    out.append("  " + ",".join("%d" % c for c in CURVE[:16]) + ",")
    out.append("  " + ",".join("%d" % c for c in CURVE[16:]))
    out.append("};")
    out.append("/* [g * 32 + b] -> 8-bit green level */")
    out.append("const unsigned char _cgb_lcd_green[32 * 32] = {")
    for g in range(32):
        row = ",".join("%d" % green(g, b) for b in range(32))
        out.append("  " + row + ("," if g < 31 else ""))
    out.append("};")
    out.append("#endif")
    # LF on every host (.gitattributes requires it for *.h).
    sys.stdout.buffer.write(("\n".join(out) + "\n").encode())


if __name__ == "__main__":
    main()
