#!/usr/bin/env bash
# make_variant.sh — build a per-game "invisible" gpSP-AdHoc variant
# (docs/VARIANTS.md): an EBOOT that looks like the game in the XMB
# (custom title + ICON0), auto-boots its baked ROM (no browser), keeps its
# saves in a private namespace (<install>/saves/), and silently negotiates
# wireless when the game itself activates the RFU adapter (ADR-0013:
# join-first-then-host on a fixed group with jittered contention backoff).
#
# Usage:
#   tools/make_variant.sh <romfile.gba> <icon0.png|-> [options]
#     --title "Name"     XMB title           (default: ROM basename)
#     --group GPSPnn     fixed wireless room (default: GPSP07)
#     --role auto|host|join   silent role    (default: auto)
#     --out DIR          output directory    (default: dist/<name>)
#   Pass "-" for the icon to skip ICON0 (XMB shows the default icon).
#
# Produces <out>/: EBOOT.PBP, <rom>, variant.ini, README.txt.  Install by
# copying the folder to ms0:/PSP/GAME/<anything>/ — paths are derived from
# the EBOOT location at runtime.  Requires the pspdev docker image and the
# core archive (gpsp_libretro_psp1.a) built in the repo root.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"

[ $# -ge 2 ] || { sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 2; }
ROM="$1"; ICON="$2"; shift 2

TITLE=""; GROUP="GPSP07"; ROLE="auto"; OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --title) TITLE="$2"; shift 2 ;;
    --group) GROUP="$2"; shift 2 ;;
    --role)  ROLE="$2";  shift 2 ;;
    --out)   OUT="$2";   shift 2 ;;
    *) echo "unknown option: $1"; exit 2 ;;
  esac
done

[ -f "$ROM" ] || { echo "FATAL: ROM not found: $ROM"; exit 1; }
[ "$ICON" = "-" ] || [ -f "$ICON" ] || { echo "FATAL: icon not found: $ICON"; exit 1; }
[ -f "$REPO/gpsp_libretro_psp1.a" ] || \
  { echo "FATAL: build the core first (make platform=psp1 in pspdev docker)"; exit 1; }
case "$ROLE" in auto|host|join) ;; *) echo "FATAL: bad --role"; exit 1 ;; esac
echo "$GROUP" | grep -qE '^[A-Za-z0-9]{1,8}$' || { echo "FATAL: group must be <=8 alnum chars"; exit 1; }

ROM_BASE="$(basename "$ROM")"
NAME="$(basename "$ROM" | sed 's/\.[^.]*$//')"
[ -n "$TITLE" ] || TITLE="$NAME"
[ -n "$OUT" ]   || OUT="$REPO/dist/$NAME"

echo "== variant: '$TITLE' (rom=$ROM_BASE group=$GROUP role=$ROLE)"
mkdir -p "$OUT"

# 1. Pack an EBOOT with the variant title/icon.  Objects are current from
#    the normal build; only mksfo/pack-pbp inputs change, so this is cheap.
ICON_ARG=""
if [ "$ICON" != "-" ]; then
  cp "$ICON" "$REPO/psp/variant_icon0.png"
  ICON_ARG='PSP_EBOOT_ICON=variant_icon0.png'
fi
docker run --rm -v "$REPO":/build -w /build/psp pspdev/pspdev sh -c \
  "rm -f PARAM.SFO EBOOT.PBP && make EBOOT.PBP PSP_EBOOT_TITLE='$TITLE' $ICON_ARG" \
  >/dev/null
cp "$REPO/psp/EBOOT.PBP" "$OUT/EBOOT.PBP"
rm -f "$REPO/psp/variant_icon0.png"

# 2. Restore the canonical EBOOT (default title, no icon).
docker run --rm -v "$REPO":/build -w /build/psp pspdev/pspdev sh -c \
  "rm -f PARAM.SFO EBOOT.PBP && make EBOOT.PBP" >/dev/null

# 3. Assemble the install folder.
cp "$ROM" "$OUT/$ROM_BASE"
cat > "$OUT/variant.ini" <<EOF
# gpSP-AdHoc per-game variant (generated by tools/make_variant.sh)
rom = $ROM_BASE
silent_wireless = 1
role = $ROLE
group = $GROUP
EOF
cat > "$OUT/README.txt" <<EOF
$TITLE — gpSP-AdHoc per-game build

Install: copy this whole folder to ms0:/PSP/GAME/$NAME/ on both PSPs.
It boots straight into the game. Saves live in the saves/ subfolder of
this install (separate from any other gpSP-AdHoc install).

Wireless is automatic: when the game itself uses its wireless features
(Union Room / Wireless Club), the PSPs find each other on room $GROUP.
Keep the WLAN switch ON. No emulator menus needed.
EOF

echo "== done: $OUT"
ls -la "$OUT"
