"""Bake the GBAdhoc wordmark into an 8-bit coverage texture.

    python tools/bake_logo.py <out.h>

Source is the wordmark already used on the EBOOT's XMB plate
(psp/assets/gbadhoc_pic1.png) -- the project's real branding, not an
approximation of it in some other font.

Stored as COVERAGE, not colour: the GE draws it through the same T8 + alpha
CLUT path the text uses, so the theme tints it (white on the dark theme,
black on the light one) and it costs one sprite.  A colour bitmap would have
to be re-authored per theme and would not match the accent.

Texture dimensions must both be powers of two -- the GE samples nothing else,
and a non-power-of-two texture does not fail loudly, it silently reads the
wrong texels.  That cost an hour on the font atlas; see font_ui.h.
"""
import os
import sys

from PIL import Image, ImageOps

SRC = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   'gpsp', 'psp', 'assets', 'gbadhoc_pic1.png')
BAND = (130, 202, 349, 238)      # the "GBAdhoc" row on the plate
TEX_W, TEX_H = 256, 32           # power of two, 8 KiB
DRAW_W, DRAW_H = 130, 22         # size it is drawn at, 480x272 native


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'gpsp/psp/logo_ui.h'
    im = Image.open(SRC).convert('L').crop(BAND)
    a = ImageOps.autocontrast(ImageOps.invert(im))       # ink -> coverage
    a = a.resize((DRAW_W, DRAW_H), Image.LANCZOS)

    tex = Image.new('L', (TEX_W, TEX_H), 0)
    tex.paste(a, (0, 0))
    data = tex.tobytes()

    with open(out, 'w', newline='\n') as fh:
        fh.write('/* GENERATED by tools/bake_logo.py -- do not edit by hand.\n'
                 ' *\n'
                 ' * The GBAdhoc wordmark from the EBOOT plate, as 8-bit\n'
                 ' * coverage for the GE\'s T8 + alpha-CLUT path.  Tinted by\n'
                 ' * the theme accent at draw time. */\n'
                 '#ifndef LOGO_UI_H\n#define LOGO_UI_H\n\n')
        fh.write('#define LOGO_TEX_W %d\n#define LOGO_TEX_H %d\n'
                 '#define LOGO_W     %d\n#define LOGO_H     %d\n\n'
                 % (TEX_W, TEX_H, DRAW_W, DRAW_H))
        fh.write('static const unsigned char __attribute__((aligned(16)))\n'
                 '   logo_a[%d] = {\n' % len(data))
        for i in range(0, len(data), 32):
            fh.write(''.join('%d,' % b for b in data[i:i + 32]) + '\n')
        fh.write('};\n\n#endif /* LOGO_UI_H */\n')
    print('wrote %s  (%dx%d drawn, %dx%d texture, %.0f KiB)'
          % (out, DRAW_W, DRAW_H, TEX_W, TEX_H, os.path.getsize(out) / 1024.0))


if __name__ == '__main__':
    main()
