#!/usr/bin/env python3
"""Bake a TTF into an 8-bit coverage atlas + glyph table as a C header.

The PSP UI used a 1-bit 8x16 bitmap font, which has no anti-aliasing and a
fixed advance.  This produces what RetroShell PSP produces: an alpha atlas
uploaded as GU_PSM_T8 with an alpha CLUT, so the GE modulates vertex colour
by glyph coverage.  Baking on the host keeps the EBOOT self-contained -- no
runtime font asset to ship or lose.

Usage: bake_font.py <out.h>
"""
import sys, os
from PIL import Image, ImageFont, ImageDraw

FIRST, LAST = 0x20, 0x7E
FONTS = os.path.join(os.path.dirname(__file__), '..',
                     'scratchpad-fonts')   # overridden below

# Atlas dimensions MUST BOTH be powers of two: the PSP's GE samples nothing
# else, and a non-power-of-two height does not fail loudly -- it silently
# reads the wrong texels, so every glyph draws as a smeared neighbour while
# the layout stays perfect.  A 256x96 `ui` atlas cost an hour of staring at
# text that was almost right.
FACES = [
    # name,  file,                px, atlas w/h
    ('ui',   'Inter-Regular.ttf',  15, 256, 128),
    ('hd',   'Inter-SemiBold.ttf', 19, 256, 128),
]


def bake(name, path, px, aw, ah):
    if aw & (aw - 1) or ah & (ah - 1):
        raise SystemExit('%s: atlas %dx%d is not power-of-two' % (name, aw, ah))
    font = ImageFont.truetype(path, px)
    asc, desc = font.getmetrics()
    atlas = Image.new('L', (aw, ah), 0)
    glyphs = []
    pen_x = pen_y = 0
    row_h = 0
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        adv = int(round(font.getlength(ch)))
        bbox = font.getbbox(ch)            # (x0, y0, x1, y1) from the origin
        if bbox is None:
            bbox = (0, 0, 0, 0)
        x0, y0, x1, y1 = bbox
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        if w and h:
            if pen_x + w + 1 > aw:
                pen_x = 0
                pen_y += row_h + 1
                row_h = 0
            if pen_y + h > ah:
                raise SystemExit('%s: atlas %dx%d too small' % (name, aw, ah))
            cell = Image.new('L', (w, h), 0)
            ImageDraw.Draw(cell).text((-x0, -y0), ch, font=font, fill=255)
            atlas.paste(cell, (pen_x, pen_y))
            glyphs.append((pen_x, pen_y, w, h, x0, y0, adv))
            pen_x += w + 1
            row_h = max(row_h, h)
        else:
            glyphs.append((0, 0, 0, 0, 0, 0, adv))
    return asc, desc, atlas, glyphs


def main():
    out = sys.argv[1]
    src = sys.argv[2]
    parts = ['/* GENERATED by tools/bake_font.py -- do not edit by hand.\n'
             ' *\n'
             ' * Inter (SIL Open Font License 1.1) baked to 8-bit coverage\n'
             ' * atlases.  See THIRD_PARTY.md. */\n'
             '#ifndef FONT_UI_H\n#define FONT_UI_H\n\n'
             '#define FU_FIRST %d\n#define FU_LAST  %d\n'
             '#define FU_COUNT (FU_LAST - FU_FIRST + 1)\n\n'
             'typedef struct {\n'
             '   unsigned short x, y;\n'
             '   unsigned char  w, h;\n'
             '   signed char    xoff, yoff, xadv;\n'
             '} fu_glyph;\n\n' % (FIRST, LAST)]
    for name, fn, px, aw, ah in FACES:
        asc, desc, atlas, glyphs = bake(name, os.path.join(src, fn), px, aw, ah)
        parts.append('/* %s: %s @%dpx, ascent %d, descent %d */\n'
                     % (name, fn, px, asc, desc))
        parts.append('#define FU_%s_W   %d\n#define FU_%s_H   %d\n'
                     '#define FU_%s_ASC %d\n#define FU_%s_LH  %d\n'
                     % (name.upper(), aw, name.upper(), ah,
                        name.upper(), asc, name.upper(), asc + desc))
        parts.append('static const fu_glyph fu_%s_g[FU_COUNT] = {\n' % name)
        for g in glyphs:
            parts.append('   {%d,%d,%d,%d,%d,%d,%d},\n' % g)
        parts.append('};\n')
        data = atlas.tobytes()
        # The GE reads texture data straight out of RAM and needs a 16-byte
        # aligned base.  Without this the sampler starts a few bytes into the
        # atlas and EVERY glyph draws as a smeared neighbour -- the layout
        # stays perfect, so it reads as a font bug rather than an alignment
        # one.  The two atlases differed only in where the linker put them.
        parts.append('static const unsigned char __attribute__((aligned(16)))'
                     ' fu_%s_a[%d] = {\n' % (name, len(data)))
        for i in range(0, len(data), 32):
            parts.append(''.join('%d,' % b for b in data[i:i + 32]) + '\n')
        parts.append('};\n\n')
    parts.append('#endif /* FONT_UI_H */\n')
    open(out, 'w', newline='\n').write(''.join(parts))
    print('wrote %s (%.0f KiB)' % (out, os.path.getsize(out) / 1024.0))


main()
